/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import javax.swing.JTextField;
import controller.pembeliantempcontroller;
import javax.swing.JTable;

/**
 *
 * @author MSI GF63
 */
public class PembelianFrame extends javax.swing.JFrame {
    pembeliantempcontroller dc;
    public String harga_barangtxt;
    public String id_pembeliantxt1;
    
    
    /**
     * Creates new form PembelianFrame
     */
    public PembelianFrame() {
        initComponents();
        dc = new pembeliantempcontroller(this);
        dc.isitabelbarang();
        dc.isitabelbeli();
    }

    public JTextField getJumlah_belitxt() {
        return jumlah_belitxt;
    }

    public void setJumlah_belitxt(JTextField jumlah_belitxt) {
        this.jumlah_belitxt = jumlah_belitxt;
    }

    public JTextField getNama_barangtxt() {
        return nama_barangtxt;
    }

    public void setNama_barangtxt(JTextField nama_barangtxt) {
        this.nama_barangtxt = nama_barangtxt;
    }

    public JTable getTabel_pembelian() {
        return tabel_pembelian;
    }

    public void setTabel_pembelian(JTable tabel_pembelian) {
        this.tabel_pembelian = tabel_pembelian;
    }

    public JTable getTabeldatabarang() {
        return tabeldatabarang;
    }

    public void setTabeldatabarang(JTable tabeldatabarang) {
        this.tabeldatabarang = tabeldatabarang;
    }

    public String getHarga_barangtxt() {
        return harga_barangtxt;
    }

    public void setHarga_barangtxt(String harga_barangtxt) {
        this.harga_barangtxt = harga_barangtxt;
    }

    public JTextField getId_pembeliantxt() {
        return id_pembeliantxt;
    }

    public void setId_pembeliantxt(JTextField id_pembeliantxt) {
        this.id_pembeliantxt = id_pembeliantxt;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        tambahbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldatabarang = new javax.swing.JTable();
        deletebtn = new javax.swing.JButton();
        jumlah_belitxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_pembelian = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nama_barangtxt = new javax.swing.JTextField();
        id_pembeliantxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        back2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Jumlah");

        tambahbtn.setText("Tambah");
        tambahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahbtnActionPerformed(evt);
            }
        });

        tabeldatabarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldatabarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldatabarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldatabarang);

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        jumlah_belitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_belitxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Barang");

        tabel_pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pembelianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_pembelian);

        nama_barangtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_barangtxtActionPerformed(evt);
            }
        });

        id_pembeliantxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pembeliantxtActionPerformed(evt);
            }
        });

        jLabel5.setText("ID Pembelian");

        back2.setText("Back");
        back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlah_belitxt)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_barangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deletebtn)
                                .addGap(76, 76, 76)
                                .addComponent(back2))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambahbtn)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_pembeliantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(922, 922, 922))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_pembeliantxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(nama_barangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah_belitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(tambahbtn)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletebtn)
                            .addComponent(back2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahbtnActionPerformed
        // TODO add your handling code here:
        dc.insert();
        dc.isitabelbeli();
        dc.isitabelbarang();
        dc.clear();

    }//GEN-LAST:event_tambahbtnActionPerformed

    private void tabeldatabarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldatabarangMouseClicked
        int baris = tabeldatabarang.getSelectedRow();
        nama_barangtxt.setText(tabeldatabarang.getValueAt(baris, 1).toString());
       harga_barangtxt = tabeldatabarang.getValueAt(baris, 2).toString();
         // TODO add your handling code here:
    }//GEN-LAST:event_tabeldatabarangMouseClicked

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        dc.delete();
        dc.isitabelbeli();
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jumlah_belitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_belitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_belitxtActionPerformed

    private void nama_barangtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_barangtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_barangtxtActionPerformed

    private void id_pembeliantxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pembeliantxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pembeliantxtActionPerformed

    private void tabel_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pembelianMouseClicked
       int baris = tabel_pembelian.getSelectedRow();
       id_pembeliantxt1 = tabel_pembelian.getValueAt(baris, 3).toString();
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_pembelianMouseClicked

    private void back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2ActionPerformed
        // TODO add your handling code here:
        new mainv().setVisible(true);
        dispose();
    }//GEN-LAST:event_back2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembelianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembelianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembelianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembelianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembelianFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JButton back2;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField id_pembeliantxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah_belitxt;
    private javax.swing.JTextField nama_barangtxt;
    private javax.swing.JTable tabel_pembelian;
    private javax.swing.JTable tabeldatabarang;
    private javax.swing.JButton tambahbtn;
    // End of variables declaration//GEN-END:variables
}
